mj:
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  accounts:
    - user-token: "${DISCORD_USER_TOKEN}"  
      guild-id: "${DISCORD_SERVER_ID}"  
      channel-id: "${DISCORD_CHANNEL_ID}" 
      user-agent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36"